runtime: custom
env: flex

# URL will be: social-network-x-dot-cs651project-jolene-474417.uc.r.appspot.com
service: social-network-x

# This configuration uses the flexible environment with a custom Docker runtime
# The Dockerfile will handle the build and run process

# Automatic scaling configuration
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.6

# Resources
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# Health check
readiness_check:
  path: "/api/config"
  check_interval_sec: 10
  timeout_sec: 10
  failure_threshold: 3
  success_threshold: 2
  app_start_timeout_sec: 600

liveness_check:
  path: "/api/config"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 4
  success_threshold: 2
  initial_delay_sec: 600

# Environment variables (set these in App Engine settings or via gcloud)
env_variables:
  NODE_ENV: production
  EXPRESS_PORT: "3001"
  EXPRESS_API_URL: "http://localhost:3001"

# Note: You'll need to set these environment variables in App Engine:
# - FIREBASE_PROJECT_ID (or FIREBASE_SERVICE_ACCOUNT)
# - FIREBASE_STORAGE_BUCKET
# - NEXT_PUBLIC_APP_URL (your App Engine URL)
# - Any other environment variables your app needs

